### PR TITLE
3 - Create UI to show top artists

### LINKED ISSUE #3: Create UI to show top artists

### PR DESCRIPTION
**Pull request by sergei-butko**
3 - Create UI to show top artists

### CODE REVIEW

**Comment by stasOR41k** [comment]
Can you please add screenshots how it looks like?

**Comment by sergei-butko** [comment]
image
image
image

**Comment by stasOR41k** [comment]
While we don't have an image functinality, lets random change the background color of the artist

**Comment by sergei-butko** [comment]
Add colorful background to artists' blocks.

image
image

**Comment by stasOR41k** [comment]
> Add colorful background to artists' blocks.
> 
> image
> image

Awesome 😍

**Review by stasOR41k — APPROVED** [review]

**Pull request merged**
